server:
  port: 9527
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh_get #路由的id，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://payment-service
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由
            #- After=2021-06-04T15:51:37.485+08:00[Asia/Shanghai]       #可以设置其他断言

        - id: payment_routh_lb #路由的id，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://payment-service
          predicates:
            - Path=/payment/lb/** #断言，路径相匹配的进行路由

eureka:
  instance:
    hostname: gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
