server:
  port: 9001
spring:
  application:
    name: alibaba-payment
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.01:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
